version : '3.8'
services:
        cypress_compose:
            build:
                context: ./
                dockerfile: ./Dockerfile
            volumes:
                - ./dockerReports:/app/allure-results


